# Generated by Django 3.1.2 on 2020-11-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
