# Generated by Django 3.1.2 on 2020-11-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201111_1139'),
    ]

    operations = [
    ]
